services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
      target: dev
    # command: "pipenv run python src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/code/src:cached
      - /home/code/.venv

volumes:
  postgres-data:
  redis-data:
