# Generated by Django 4.2.7 on 2023-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('signup_start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('signup_end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contest_start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contest_end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('judging_start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('judging_end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
