# Generated by Django 4.2.7 on 2023-11-21 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('entries', '0001_initial'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[['code_quality', 'Code Quality'], ['design', 'Design'], ['idea', 'Idea'], ['execution', 'Execution']], default='code_quality', max_length=32)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text=('Values 1-5. Decimals allowed, up to two decimal places (e.g. `2.25`).',), max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.competition')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='entries.entry')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.judge')),
            ],
            options={
                'unique_together': {('competition', 'judge', 'entry', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_quality_score', models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text=('Values 1-5. Decimals allowed, up to two decimal places (e.g. `2.25`).',), max_digits=3)),
                ('design_score', models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text=('Values 1-5. Decimals allowed, up to two decimal places (e.g. `2.25`).',), max_digits=3)),
                ('idea_score', models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text=('Values 1-5. Decimals allowed, up to two decimal places (e.g. `2.25`).',), max_digits=3)),
                ('execution_score', models.DecimalField(blank=True, decimal_places=2, default='0.0', help_text=('Values 1-5. Decimals allowed, up to two decimal places (e.g. `2.25`).',), max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='entries.entry')),
                ('prizes', models.ManyToManyField(related_name='results', to='sponsors.prize')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='teams.team')),
            ],
            options={
                'unique_together': {('competition', 'team', 'entry')},
            },
        ),
    ]
